on:
  push:
    # branches:
    #   - release

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.10.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build
      run: flet publish main.py --assets assets/ --base-url Dottore-Genius-Invokation-TCG-PWA

    - uses: actions/upload-artifact@v3
      with:
        name: page
        path: dist
        if-no-files-found: error

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/release'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: page
        path: dist
    - uses: actions/upload-pages-artifact@v2
      with:
        path: dist
    - id: deployment
      uses: actions/deploy-pages@v2